#!/bin/sh

touch /mnt/raid0/logs/full_read_all_drives/started-$(date +%m-%d-%y--%I-%M-%p)

# /dev/md0
dd if=/dev/disk/by-uuid/e944a45c-e37f-414a-88e6-d0bed8b3b302 of=/dev/null bs=64K
#/dev/md1
dd if=/dev/disk/by-uuid/2040a920-fdaa-4907-91e7-0d7cc230c7b3 of=/dev/null bs=64K

touch /mnt/raid0/logs/full_read_all_drives/ended-$(date +%m-%d-%y--%I-%M-%p)
