#!/bin/sh

/usr/bin/rsync -azPi --delete --exclude=/USB_OS --exclude /mnt \
--exclude /var/log --exclude /sys  --exclude /proc --exclude /tmp \
--exclude /run/ --exclude /dev \
/ /USB_OS/ >  /mnt/raid0/logs/ram_backup/$(date +%m-%d-%y--%I-%M-%p)

