#!/bin/bash
# This is a sample shell script showing how you can submit the PROCESS_SERVICE_CHECK_RESULT command
# to Nagios.  Adjust variables to fit your environment as necessary.

now=`date +%s`
commandfile='/usr/local/nagios/var/rw/nagios.cmd'
NAGIOS_COMMAND_URL="http://172.16.2.100:25003/submit_nagios_command"

# determine the drives to check
chars=( {a..z} )
n=9

# Loop through each drive and run the check
for ((i=0;i<n; i++))
do
    c="${chars[i]}"
    drive_name=sd${c}
#   echo $c
    command=`sudo /usr/lib/nagios/plugins/check_ide_smart /dev/${drive_name}`
    check_output=`/usr/bin/printf "[%lu] PROCESS_SERVICE_CHECK_RESULT;nas;Smart Status %s;%s;%s\n" $now "$drive_name" "$?" "$command"`
    curl -X POST -d "$check_output" $NAGIOS_COMMAND_URL
done

