#!/bin/bash

if [ "$1" == "case" ]
then
	out=$(cat /sys/bus/w1/devices/28-000004f236cf/w1_slave | grep -oP 't=\s*\K\d+')

	f_degrees=$(echo "scale=5; (1.8*$out/1000 + 32)" | bc)

	# Threshold is 68 degrees F
	echo "Case Temperature:" $f_degrees"F"

	if [ $( printf "%.0f" $f_degrees ) -gt 71 ]
	then
	        exit 2
	else
	        exit 0
	fi
else
	command_output=$(sudo /usr/local/nagios/libexec/AdafruitDHT 11 18)
	out=$(echo "$command_output" | grep -oP 'Temp = \d+' |  grep -oP '\d+')
 	humidity=$(echo "$command_output" | grep -oP 'Hum = \d+' |  grep -oP '\d+')	
	f_degrees=$(echo "scale=5; (1.8*$out+ 32)" | bc)

        # Threshold is 70 degrees F
        echo "Basement Temperature:" $f_degrees"F Humidity:" $humidity

        if [ $( printf "%.0f" $f_degrees ) -gt 73 ]
        then
                exit 2
        else
                exit 0
        fi
fi

