#!/bin/bash

# SET TEMP DIR
export -p TMPDIR=/mnt/raid0/tmp_dir

array=("win7" "dad-vm")
image_file_names=("avi-pc.qcow2" "dad-vm.qcow2")
wait_time=1.5 # How long to wait after shutting

for one_item in "${!array[@]}"
do
    MACHINE_NAME=${array[one_item]}
    IMAGE_FILE=${image_file_names[$one_item]}
    SRC_FILE=/mnt/vm_drive_ssd/vm_drives/$IMAGE_FILE
    DEST_FILE=/mnt/vm_drive_raid1/ssd_vm_drives/$IMAGE_FILE

    echo "Shutting down $MACHINE_NAME"
    virsh shutdown $MACHINE_NAME
    echo "Waiting $wait_time m for shutdown of $MACHINE_NAME"
    sleep ${wait_time}m

    echo "Using virt-sparsify to copy image $SRC_FILE to $DEST_FILE"
    virt-sparsify $SRC_FILE $DEST_FILE

    echo "Starting up $MACHINE_NAME"
    virsh start $MACHINE_NAME
done
