#! /bin/bash

DATE=`date +%Y-%m-%d-%H-%M-%S`
# Redirect output to file
exec 3>&1 1>> /mnt/raid0/logs/linux_vms_backup/logfile-${DATE}.txt 2>&1

set -o xtrace
# SET TEMP DIR
export -p TMPDIR=/mnt/raid0/tmp_dir

# Declare vm names and image names for backup
array=("linux-desktop" "freepbx" "torrent-box" "mysql-server" "dev-machine")
image_file_names=("linux-desktop.qcow2" "freepbx-cd.qcow2" "seedbox.qcow2" "mysql-server.qcow2" "dev-machine.qcow2")

for one_item in "${!array[@]}"
do
    MACHINE_NAME=${array[one_item]}
    IMAGE_FILE=${image_file_names[$one_item]}
    SRC_FILE=/mnt/raid0/vm_drives/$IMAGE_FILE
    DEST_FILE=/mnt/vm_drive_raid1/vm_drives/$IMAGE_FILE
    SNAPSHOT_NAME=backup-snapshot-${MACHINE_NAME}-${DATE}
    SNAPSHOT_FILE=/mnt/raid0/vm_drives/${SNAPSHOT_NAME}.qcow2

    # Dump xml for machine
    /usr/bin/virsh dumpxml $MACHINE_NAME > /mnt/vm_drive_raid1/vm_drives/${MACHINE_NAME}.xml && \
    /usr/bin/virsh domblklist $MACHINE_NAME && \
    /usr/bin/virsh snapshot-create-as --domain $MACHINE_NAME $SNAPSHOT_NAME --diskspec vda,file=$SNAPSHOT_FILE --quiesce --disk-only --atomic --no-metadata && \
    /usr/bin/virsh domblklist $MACHINE_NAME && \
    /usr/bin/virt-sparsify $SRC_FILE $DEST_FILE && \
    
    /usr/bin/virsh blockcommit $MACHINE_NAME vda --active --verbose --pivot && \
    /usr/bin/virsh domblklist $MACHINE_NAME && \
    # Remove old snapshot. Currently isnt needed as we create snapshot without metadata
#   virsh snapshot-delete $MACHINE_NAME --metadata $SNAPSHOT_NAME
    # delete from disk
    touch /mnt/vm_drive_raid1/vm_drives/
    rm $SNAPSHOT_FILE
done

